CREATE TABLE filme (
id BIGSERIAL PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
assistido BOOLEAN DEFAULT FALSE,
genero_id BIGINT,
FOREIGN KEY (genero_id) REFERENCES genero(id) ON DELETE NO ACTION
);